/********************************************************************
* /home/dglazier/Dropbox/hsana/Events/ExtraPackages/eloss_hs/elossDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/dglazier/Dropbox/hsana/Events/ExtraPackages/eloss_hs/elossDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableelossDict();
extern void G__cpp_setup_inheritanceelossDict();
extern void G__cpp_setup_typetableelossDict();
extern void G__cpp_setup_memvarelossDict();
extern void G__cpp_setup_globalelossDict();
extern void G__cpp_setup_memfuncelossDict();
extern void G__cpp_setup_funcelossDict();
extern void G__set_cpp_environmentelossDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/dglazier/Dropbox/hsana/Events/ExtraPackages/eloss_hs/eLoss.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__elossDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__elossDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__elossDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__elossDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__elossDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__elossDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__elossDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__elossDictLN_TVector3;
extern G__linked_taginfo G__elossDictLN_TLorentzVector;

/* STUB derived class for protected member access */
